name: Cargo Deny

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
